// function showElement(element) {
//     alert("you clicked: " + element);
    
// }

const elementData = {
    H:{
        name:"Hydrogen",
        number:1,
        category:"non-metal"
    },
    He:{
        name:"Helium",
        number:2,
        category:"non-metal"
    },
    Li:{
        name:"Lithium",
        number:3,
        category:"metal"
    },

    Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     B:{
        name:"Boron",
        number:5,
        category:"metal"
    },
     C:{
        name:"Carbon",
        number:6,
        category:"non-metal",
        electronicConfiguration: "2s"
    },
    
     N:{
        name:"Nitrogen",
        number:7,
        category:"non-metal"
    },
    
     O:{
        name:"Beryllium",
        number:8,
        category:"non-metal"
    },
     F:{
        name:"Beryllium",
        number:9,
        category:"non-metal"
    },
     Ne:{
        name:"Beryllium",
        number:10,
        category:"nobal-gas"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
     Be:{
        name:"Beryllium",
        number:4,
        category:"metal"
    },
};
document.addEventListener("DOMContentLoaded", function() {
    const elements = document.querySelectorAll("td[data-element]");

elements.forEach( function(element)  {
    element.addEventListener("click" , function () {
        let symbol = this.dataset.element;
        let data = elementData[symbol];

        console.log(data.name);
        console.log(data.number);
        console.log(data.category);
        console.log(data.electronicConfiguration);
        
        // console.log(this.dataset.element);
    })
})
})



